### ISSUE TITLE
Request to migrate zypprepo to VoxPupuli

### ISSUE THREAD

**Issue by noqqe** [voxpupuli/puppet-zypprepo#15]
Hi,

I am suggesting a migration of this puppet module to VoxPupuli as it does not seem to be maintained. 

See https://voxpupuli.org/docs/ for migration steps

If you need help or being not interested please state both in the comments below @deadpoint.

**Comment by deadpoint** [comment]
I'm no longer using Puppet nor am I maintaining this module and support migrating it an active maintainer.

**Comment by bastelfreak** [comment]
Hi @deadpoint,

I'm one of the Vox Pupuli adminsitrators. We have detailed migration documentation on https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

I added you to our org on github, you now have permission to transfer the repository to us.  If you've any questions feel free to join our IRC channel #voxpupuli on freenode.

**Comment by mmoll** [comment]
this seems to have been transferred by now...

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/modulesync_config/pull/348
https://github.com/voxpupuli/modulesync_config/pull/349
https://github.com/voxpupuli/plumbing/pull/132
https://github.com/voxpupuli/puppet-zypprepo/pull/16

----

I created several needed pull requests. Once the modulesync is merged we can do a new release of the module in our namespace.

**Comment by alexjfisher** [comment]
2.0.0 has been released to the forge under the new namespace. https://forge.puppet.com/puppet/zypprepo
