### ISSUE TITLE
ability to remove repo

### ISSUE THREAD

**Issue by tampakrap** [voxpupuli/puppet-zypprepo#5]
We need an ensure => present/absent in order to be able to remove a zypprepo

**Comment by deadpoint** [comment]
When this was written it was derived from yumrepo which did not have the ability to remove repos either.  The current yumrepo has been rewritten to use Puppet::Type.newtype which supports 'ensurable' so adding this functionality is a one-liner. I rewrite shouldn't take too much effort, however I don't really have to time to devote to this at the momemt. Having said that if you're feeling ambitious I'll gladly accept a pull request;-)

https://docs.puppetlabs.com/guides/complete_resource_example.html

**Comment by tampakrap** [comment]
Sure, I am going to work on this one. I filed the bug so I don't forget it actually, apologies for not mentioning initially that I'm going to handle it

**Comment by rwaffen** [comment]
I'm not so good with provides/types ... but is there an update after the last 4 years? :D
