### ISSUE TITLE
PDK and add tests

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/puppet-zypprepo#53]
This module is not PDK compatible and has missing tests for the type/provider.

Required activities:
1. pdk convert - allow execution of unit tests via PDK
2. unit tests for zypprepo type/provider

**Comment by alexjfisher** [comment]
We don't have a PDK workflow.  Our modulesync setup has got considerably more advanced recently too, as well as a switch to github workflows.

**Comment by tuxmea** [comment]
Oh. OK. I modulesync already activated for this module?
