### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mx-psi** [voxpupuli/puppet-zypprepo#56]
Hi, I was wondering if it would be possible to make a new release that includes PR #55. Last year I contributed PR #48 which was unfortunately accidentally reverted on #52 (see https://github.com/voxpupuli/puppet-zypprepo/pull/52#discussion_r553923594) and so never made it into the 3.1.0 release. 

Since PR #55 adds back my contribution, I would be grateful if a release was made that included the changes on this PR.

Thanks!

**Comment by tuxmea** [comment]
+1

**Comment by dadav** [comment]
+1 :)
