### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by eabecho** [voxpupuli/puppet-zypprepo#8]
Can you add version number labels/releases so this module can be used in a production environment?  Thanks!

**Comment by deadpoint** [comment]
I'm not sure what you mean by this, the current version is 1.0.2 and can be installed with 'puppet module darin-zypprepo' or upgraded with 'puppet module upgrade darin-zypprepo'

**Comment by tampakrap** [comment]
he asks for git tag

**Comment by eabecho** [comment]
Yes, a git tag.  Otherwise, we can only check out the latest version.  We need to be able to check out a specific version via a git tag.

**Comment by deadpoint** [comment]
thanks for clarifying

**Comment by eabecho** [comment]
Any updates?  Thanks.

**Comment by llowder** [comment]
+1 on this. I'm having to create tags locally which is less than ideal

**Comment by razorsedge** [comment]
@alexjfisher @igalic @bastelfreak Can we get commit 1e89a533d1573061cc3e75984ae6386d0afeb85b tagged with v1.0.2 please?

**Comment by igalic** [comment]
@razorsedge would you like to make a PR for release? https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module

**Comment by razorsedge** [comment]
@igalic I don't want a new release.  I would like a git tag on the old releases so that I can pin to that tag in my .fixtures.yml.

**Comment by alexjfisher** [comment]
@razorsedge How's that?

**Comment by razorsedge** [comment]
@alexjfisher Actually, my bad.  The tag should be 1.0.2 without the leading "v".  Otherwise it is good.

**Comment by alexjfisher** [comment]
Our release process creates tags *with* leading 'v's.
https://github.com/voxpupuli/puppet-zypprepo/tags

You should still be able to use this in your .fixtures?

**Comment by alexjfisher** [comment]
@razorsedge You probably already know, but you can also use forge modules in .fixtures.yml

**Comment by razorsedge** [comment]
@alexjfisher Yes, the leading "v" works as well.  And apparently I had forgotten about using forge modules in .fixtures.yml.  Thanks.
